### ISSUE TITLE
add output featureType parameter as input to /location/overlap

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-integration-api#31]
Requirement is for the /location/overlap endpoint to include a parameter to specify `output_featuretype_uri`. That would allow clients and users to filter by specific feature types like asgs:StatisticalAreaLevel2 or geofabric:ContractedCatchment.

**Comment by benjaminleighton** [comment]
A fully qualified resource type like http://linked.data.gov.au/def/asgs#MeshBlock can be specified on a new 'output_featuretype_uri' this will filter the results list of all modes of the 'overlaps' endpoint and return only those overlapping features that match the specified type. 

Internally this works by through a function that runs a SPARQL query to check if a result conforms to the specified feature type. The initial results list has all objects and doesn't limit the initial U shaped query to a particular linkset. In the future it would be good to refine the functionality so that in the internal 'overlaps' functions the SPARQL is restricted to look at a particular linkset applicable to the input and output feature types. 

Broadly this might work by:

```
PREFIX loci: <http://linked.data.gov.au/def/loci#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
select distinct ?g where { 
    GRAPH ?g {
    	?s a geo:Feature .
        ?s a ?type
        FILTER(?s = <http://linked.data.gov.au/dataset/asgs2016/meshblock/70014940000>)
	}	
} limit 100 
``` to find a candidate "to" or "from" linkset dataset and then another sparql query to appropriately filter the desired linksets. I suggest this goes in a new issue.
